# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Fri Mar 26 10:44:20 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 161)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_source = QtWidgets.QLineEdit(self.centralwidget)
        self.line_source.setEnabled(True)
        self.line_source.setReadOnly(True)
        self.line_source.setObjectName("line_source")
        self.horizontalLayout.addWidget(self.line_source)
        self.button_source = QtWidgets.QPushButton(self.centralwidget)
        self.button_source.setObjectName("button_source")
        self.horizontalLayout.addWidget(self.button_source)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_target = QtWidgets.QLineEdit(self.centralwidget)
        self.line_target.setEnabled(True)
        self.line_target.setReadOnly(True)
        self.line_target.setObjectName("line_target")
        self.horizontalLayout_2.addWidget(self.line_target)
        self.button_target = QtWidgets.QPushButton(self.centralwidget)
        self.button_target.setObjectName("button_target")
        self.horizontalLayout_2.addWidget(self.button_target)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spin_memory = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_memory.setObjectName("spin_memory")
        self.horizontalLayout_3.addWidget(self.spin_memory)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spin_blur = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_blur.setObjectName("spin_blur")
        self.horizontalLayout_3.addWidget(self.spin_blur)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.double_spin_threshold = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.double_spin_threshold.setMaximum(1.0)
        self.double_spin_threshold.setSingleStep(0.05)
        self.double_spin_threshold.setProperty("value", 0.3)
        self.double_spin_threshold.setObjectName("double_spin_threshold")
        self.horizontalLayout_3.addWidget(self.double_spin_threshold)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.double_spin_size = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.double_spin_size.setMaximum(1.0)
        self.double_spin_size.setSingleStep(0.01)
        self.double_spin_size.setProperty("value", 1.0)
        self.double_spin_size.setObjectName("double_spin_size")
        self.horizontalLayout_3.addWidget(self.double_spin_size)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.double_spin_roimulti = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.double_spin_roimulti.setMinimum(0.8)
        self.double_spin_roimulti.setMaximum(10.0)
        self.double_spin_roimulti.setSingleStep(0.05)
        self.double_spin_roimulti.setProperty("value", 1.0)
        self.double_spin_roimulti.setObjectName("double_spin_roimulti")
        self.horizontalLayout_4.addWidget(self.double_spin_roimulti)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progress.setEnabled(True)
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.horizontalLayout_5.addWidget(self.progress)
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setObjectName("button_start")
        self.horizontalLayout_5.addWidget(self.button_start)
        self.button_abort = QtWidgets.QPushButton(self.centralwidget)
        self.button_abort.setEnabled(False)
        self.button_abort.setObjectName("button_abort")
        self.horizontalLayout_5.addWidget(self.button_abort)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "DashcamCleaner", None, -1))
        self.button_source.setText(QtWidgets.QApplication.translate("MainWindow", "Select video", None, -1))
        self.button_target.setText(QtWidgets.QApplication.translate("MainWindow", "Select target", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Frame memory:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Blur size:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Detection threshold:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Inference scale", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "ROI enlargement", None, -1))
        self.button_start.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.button_abort.setText(QtWidgets.QApplication.translate("MainWindow", "Abort", None, -1))

